apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-liberal-chigger
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "368332740718"
    project: complexica-demo
    provider: gke
    registry: gcr.io
    zone: australia-southeast1-a
  environments:
  - key: dev
    owner: centreau
    repository: jx-demo-cluster-01
  - key: staging
  - key: production
  ingress:
    domain: 34.116.90.205.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  kuberhealthy: true
  pipelineUser:
    username: voyen-bot
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-liberal-chigger-f4477a6fd2f3
  - name: reports
    url: gs://reports-tf-jx-liberal-chigger-f4477a6fd2f3
  - name: repository
    url: gs://repository-tf-jx-liberal-chigger-f4477a6fd2f3
  vault: {}
  webhook: lighthouse
